spring.application.name=A3.QUIZ

# URL de conexão apontando para o banco criado no Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/a3_quiz_db
spring.datasource.username=liz_developer
spring.datasource.password=123456

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect