spring.application.name=A3.QUIZ

spring.datasource.url=${postgresql://a3_postgres_user:I43MMeN3O4YV6FKhOrgjmMTpID1vNAug@dpg-d8b8katckfvc73cpjdn0-a/a3_postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always