spring.application.name=A3.QUIZ

# Conexão com o banco PostgreSQL no Render
spring.datasource.url=jdbc:postgresql://dpg-d8b8katckfvc73cjdn0-a.oregon-postgres.render.com/a3_postgres?sslmode=require
spring.datasource.username=a3_postgres_user
spring.datasource.password=I43MMeN304YV6FKh0rgjmMTpID1vNAug
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate para manter as tabelas sincronizadas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração da porta para o Render (e fallback para localhost)
server.port=${PORT:8080}
